#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Android_Controls.Resource", IsApplication=true)]

namespace Android_Controls
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int country_arrays = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060002
			public const int Android = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int Button = 2131099648;
			
			// aapt resource value: 0x7f06000c
			public const int CheckBox = 2131099660;
			
			// aapt resource value: 0x7f060004
			public const int DatePicker = 2131099652;
			
			// aapt resource value: 0x7f06000b
			public const int EditText = 2131099659;
			
			// aapt resource value: 0x7f060014
			public const int Female = 2131099668;
			
			// aapt resource value: 0x7f060009
			public const int GridView = 2131099657;
			
			// aapt resource value: 0x7f060001
			public const int Ios = 2131099649;
			
			// aapt resource value: 0x7f06000a
			public const int ListView = 2131099658;
			
			// aapt resource value: 0x7f060013
			public const int Male = 2131099667;
			
			// aapt resource value: 0x7f060008
			public const int PasswordEditText = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int PasswordTextView = 2131099655;
			
			// aapt resource value: 0x7f06000d
			public const int RadioButton = 2131099661;
			
			// aapt resource value: 0x7f060012
			public const int Sex = 2131099666;
			
			// aapt resource value: 0x7f06000f
			public const int Spinner = 2131099663;
			
			// aapt resource value: 0x7f060006
			public const int TextEditText = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int TextTextView = 2131099653;
			
			// aapt resource value: 0x7f060010
			public const int TimePicker = 2131099664;
			
			// aapt resource value: 0x7f06000e
			public const int ToggleButton = 2131099662;
			
			// aapt resource value: 0x7f060015
			public const int ToggleButton1 = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int ToggleButton2 = 2131099670;
			
			// aapt resource value: 0x7f060011
			public const int WebView = 2131099665;
			
			// aapt resource value: 0x7f060003
			public const int Windows = 2131099651;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Button = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CheckBox = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int DatePicker = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int EditText = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int GridView = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ImageView = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ListItem = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int ListView = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Main = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int RadioButton = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Spinner = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int TimePicker = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int ToggleButton = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int WebView = 2130903053;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int country_prompt = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
